apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: dvwa-web
    namespace: hz001
    uid: a479104e-6507-11e6-a557-00163e026acf
  spec:
    containers:
    - image: index.caicloud.io/markthink/dvwa-nginx
      imagePullPolicy: Always
      name: nginx
      ports:
      - containerPort: 80
        protocol: TCP
      volumeMounts:
      - mountPath: /dvwa/htdocs/dvwa_app
        name: dvwa-data
      - mountPath: /etc/nginx/conf.d/
        name: nginx-web
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 1Mi    
    - image: index.caicloud.io/markthink/dvwa-php
      imagePullPolicy: Always
      name: php
      ports:
      - containerPort: 8000
        protocol: TCP
      - containerPort: 9000
        protocol: TCP
      volumeMounts:
      - mountPath: /dvwa/htdocs/dvwa_app
        name: dvwa-data
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 1Mi
    - env:
      - name: MYSQL_ROOT_PASSWORD
        value: "123456"
      image: index.caicloud.io/markthink/dvwa-mysql
      imagePullPolicy: Always
      name: mysql
      ports:
      - containerPort: 3306
        protocol: TCP
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 1Mi
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: mysql-data
    nodeName: kubernetes-node-1
    restartPolicy: Always
    volumes:
    - hostPath:
        path: /root/pod-container/dvwa
      name: dvwa-data
    - hostPath:
        path: /root/pod-container/mysql
      name: mysql-data
    - hostPath:
        path: /root/pod-container/web
      name: nginx-web
kind: List
metadata: {}